=== shubhamfam/mcs_lab/xml/Gradebook.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT gradebook  ( grade )>
<!ELEMENT fname  ( #PCDATA )>
<!ELEMENT courses  ( course+ )>
<!ELEMENT A  ( #PCDATA )>
<!ELEMENT B  ( #PCDATA )>
<!ELEMENT C  ( #PCDATA )>
<!ELEMENT cno  ( #PCDATA )>
<!ELEMENT student  ( sid , fname , lname , minit )>
<!ELEMENT catalog  ( cno , ctitle )>
<!ELEMENT enrolls  ( enroll+ )>
<!ELEMENT students  ( student+ )>
<!ELEMENT minit  ( #PCDATA )>

<!ELEMENT sid  ( #PCDATA )>
<!ELEMENT secno  ( #PCDATA )>
<!ELEMENT lname  ( #PCDATA )>
<!ELEMENT catalogs  ( catalog+ )>
<!ELEMENT ctitle  ( #PCDATA )>
<!ELEMENT grade  ( catalogs , students , courses , enrolls )>
<!ELEMENT course  ( term , secno , cno , A , B , C )>
<!ELEMENT term  ( #PCDATA )>
<!ELEMENT enroll  ( sid , term , secno )>

=== shubhamfam/mcs_lab/XML/3.gradebook/Gradebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gradebook SYSTEM "/home/shubham/coding/mcs_lab/XML/3.gradebook/Gradebook.dtd">

<gradebook>

  <grade>

  	<catalogs>
		<catalog>
			<cno>CSc225</cno>
			<ctitle>Automata</ctitle>
		</catalog>
		<catalog>
			<cno>CSc226</cno>
			<ctitle>JAVA</ctitle>
		</catalog>
		<catalog>
			<cno>CSc227</cno>
			<ctitle>PYTHON</ctitle>
		</catalog>
		<catalog>
			<cno>CSc228</cno>
			<ctitle>AWS</ctitle>
		</catalog>
	</catalogs>
	
	<students>
		<student>
			<sid>101</sid>
			<fname>Shubham</fname>
			<lname>Gaikwad</lname>
			<minit>30</minit>
		</student>
		<student>
			<sid>102</sid>
			<fname>Wallabh</fname>
			<lname>Joshi</lname>
			<minit>45</minit>
		</student>
		<student>
			<sid>103</sid>
			<fname>Siddhant</fname>
			<lname>Bokephode</lname>
			<minit>24</minit>
		</student>
		<student>
			<sid>104</sid>
			<fname>Gaurav</fname>
			<lname>Panhalkar</lname>
			<minit>42</minit>
		</student>
		<student>
			<sid>105</sid>
			<fname>Ishan</fname>
			<lname>Dorge</lname>
			<minit>44</minit>
		</student>
		<student>
			<sid>107</sid>
			<fname>Yash</fname>
			<lname>Kalyani</lname>
			<minit>44</minit>
		</student>
	</students>
	
	<courses>
		<course>
			<term>f96</term>
			<secno>11</secno>
			<cno>CSc225</cno>
			<A>12</A>
			<B>10</B>
			<C>2</C>
		</course>
		<course>
			<term>f96</term>
			<secno>22</secno>
			<cno>CSc226</cno>
			<A>11</A>
			<B>3</B>
			<C>8</C>
		</course>
		<course>
			<term>f97</term>
			<secno>33</secno>
			<cno>CSc227</cno>
			<A>20</A>
			<B>15</B>
			<C>8</C>
		</course>
		<course>
			<term>f98</term>
			<secno>44</secno>
			<cno>CSc225</cno>
			<A>20</A>
			<B>15</B>
			<C>8</C>
		</course>
	</courses>
	
	<enrolls>
		<enroll>
			<sid>101</sid>
			<term>f96</term>
			<secno>33</secno>
		</enroll>
		<enroll>
			<sid>101</sid>
			<term>f97</term>
			<secno>22</secno>
		</enroll>
		<enroll>
			<sid>101</sid>
			<term>f97</term>
			<secno>11</secno>
		</enroll>
		<enroll>
			<sid>101</sid>
			<term>f96</term>
			<secno>44</secno>
		</enroll>
		<enroll>
			<sid>102</sid>
			<term>f95</term>
			<secno>44</secno>
		</enroll>
		<enroll>
			<sid>102</sid>
			<term>f95</term>
			<secno>22</secno>
		</enroll>
		<enroll>
			<sid>103</sid>
			<term>f96</term>
			<secno>33</secno>
		</enroll>
		<enroll>
			<sid>105</sid>
			<term>f94</term>
			<secno>22</secno>
		</enroll>
		<enroll>
			<sid>105</sid>
			<term>f96</term>
			<secno>11</secno>
		</enroll>
	</enrolls>
 </grade>
</gradebook>
